const STUDENTS_DATA = [
  {
    "sl_no": 1,
    "student_id": "adib1",
    "short_roll": "139",
    "full_class_roll": "1202526010139",
    "admission_roll": "196568",
    "hall_room": "",
    "group": "HSC - Science",
    "group_category": "Science",
    "section": "Section A",
    "practical_group": "A2",
    "name_en": "Abdullah Al Adib",
    "name_bn": "আবদুল্লাহ আল আদিব",
    "photo": "images/adib-139.jpg",
    "phone": "01625329874",
    "nid": "20097526001124282",
    "email": "adibsigmaa@gmail.com",
    "gender": "Male",
    "dob": "04-Oct-2009",
    "blood_group": "A+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "Md. Akbar Ali",
    "father_name_bn": "মোঃ আকবর আলী",
    "father_phone": "01733116384",
    "father_nid": "19807513695910962",
    "father_occ": "Teacher",
    "father_annual_income": 40000,
    "father_monthly_income": 3333,
    "mother_name_en": "Rozina Akter",
    "mother_name_bn": "রোজিনা আকতার",
    "mother_phone": "01718636978",
    "mother_nid": "1450323843",
    "local_guardian": "Mahmood Halimi 01712544248",
    "present_address": "Vill: Charkoilash, Ward No. 01, Hatiya Pouroshova, Post Office: Hatiya, Post Code: 3890, Upazila: Hatiya, District: Noakali District: Noakhali",
    "permanent_address": "Vill: Charkoilash, Ward No. 01, Hatiya Pouroshova, Post Office: Hatiya, Post Code: 3890, Upazila: Hatiya, District: Noakali District: Noakhali",
    "district": "Noakhali",
    "ssc_roll": "196568",
    "ssc_reg_no": "2211295908",
    "ssc_board": "Cumilla",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2023-2024",
    "ssc_division": "SSC - Science",
    "elective_subject": "Higher Math",
    "fourth_subject": "Statistics",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "adib-196568-139.pdf",
    "pay_pdf_filename": "adib-196568-139.pdf",
    "app_pdf_path": "Application Form/adib-196568-139.pdf",
    "pay_pdf_path": "Payment Receipts/adib-196568-139.pdf",
    "photo_filename": "adib-139.jpg",
    "district_bn": "নোয়াখালী",
    "upazila_district_bn": "হাতিয়া, নোয়াখালী"
  },
  {
    "sl_no": 2,
    "student_id": "santo2",
    "short_roll": "161",
    "full_class_roll": "1202526010161",
    "admission_roll": "196573",
    "hall_room": "",
    "group": "HSC - Science",
    "group_category": "Science",
    "section": "Section B",
    "practical_group": "B1",
    "name_en": "Naimul Islam (Shanto)",
    "name_bn": "নাইমুল ইসলাম (শান্ত)",
    "photo": "images/shanto-161.jpg",
    "phone": "01613601161",
    "nid": "20097513657108292",
    "email": "mistersanto1000@gmail.com",
    "gender": "Male",
    "dob": "08-Dec-2009",
    "blood_group": "O+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "NAZRUL ISLAM",
    "father_name_bn": "নজরুল ইসলাম",
    "father_phone": "01759034045",
    "father_nid": "19687513657944161",
    "father_occ": "Works in abroad",
    "father_annual_income": 0,
    "father_monthly_income": 0,
    "mother_name_en": "MARIUM BEGUM",
    "mother_name_bn": "মরিয়ম বেগম",
    "mother_phone": "01732853060",
    "mother_nid": "19857513657944162",
    "local_guardian": "",
    "present_address": "District: Noakhali",
    "permanent_address": "House: Nazrul Dubaier Badi Village:East Birbiri Dakghor: Jahajmara-3890 Ward no-06 District: Noakhali",
    "district": "Noakhali",
    "ssc_roll": "196573",
    "ssc_reg_no": "2211295913",
    "ssc_board": "Cumilla",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2023-2024",
    "ssc_division": "SSC - Science",
    "elective_subject": "Biology",
    "fourth_subject": "Higher Math",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "shanto-196573-161.pdf",
    "pay_pdf_filename": "shanto-196573-161.pdf",
    "app_pdf_path": "Application Form/shanto-196573-161.pdf",
    "pay_pdf_path": "Payment Receipts/shanto-196573-161.pdf",
    "photo_filename": "shanto-161.jpg",
    "district_bn": "নোয়াখালী",
    "upazila_district_bn": "জাহাজমারা, হাতিয়া, নোয়াখালী"
  },
  {
    "sl_no": 3,
    "student_id": "jahid3",
    "short_roll": "164",
    "full_class_roll": "1202526010164",
    "admission_roll": "196560",
    "hall_room": "",
    "group": "HSC - Science",
    "group_category": "Science",
    "section": "Section B",
    "practical_group": "B1",
    "name_en": "Md Zahidul Islam",
    "name_bn": "মোঃ জাহিদুল ইসলাম",
    "photo": "images/Zahid-164.jpg",
    "phone": "01346869238",
    "nid": "20107513676121278",
    "email": "zahidsigma164@gmail.com",
    "gender": "Male",
    "dob": "07-Jan-2010",
    "blood_group": "A+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "MD Zahirul Islam",
    "father_name_bn": "মোঃ জাহিরুল ইসলাম",
    "father_phone": "01747625973",
    "father_nid": "19897513676966542",
    "father_occ": "Service Holder",
    "father_annual_income": 0,
    "father_monthly_income": 0,
    "mother_name_en": "Merina Akter Akhi",
    "mother_name_bn": "মেরিনা আক্তার আঁখি",
    "mother_phone": "01746496782",
    "mother_nid": "19957513619001498",
    "local_guardian": "",
    "present_address": "Village: Sunnerchar,Ward no.08, Hatiya Pourashava,Post office: Hatiya,Post code:3890 , Upzilla: Hatiya , District: Noakhali District: Noakhali",
    "permanent_address": "Village: Sunnerchar,Ward no.08, Hatiya Pourashava,Post office: Hatiya,Post code:3890 , Upzilla: Hatiya , District: Noakhali District: Noakhali",
    "district": "Noakhali",
    "ssc_roll": "196560",
    "ssc_reg_no": "2211295899",
    "ssc_board": "Cumilla",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2023-2024",
    "ssc_division": "SSC - Science",
    "elective_subject": "Higher Math",
    "fourth_subject": "Biology",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "Zahid-196560-164.pdf",
    "pay_pdf_filename": "Zahid-196560-164.pdf",
    "app_pdf_path": "Application Form/Zahid-196560-164.pdf",
    "pay_pdf_path": "Payment Receipts/Zahid-196560-164.pdf",
    "photo_filename": "Zahid-164.jpg",
    "district_bn": "নোয়াখালী",
    "upazila_district_bn": "সুন্নেরচর, হাতিয়া, নোয়াখালী"
  },
  {
    "sl_no": 4,
    "student_id": "sakil4",
    "short_roll": "326",
    "full_class_roll": "1202526010326",
    "admission_roll": "129636",
    "hall_room": "",
    "group": "HSC - Science",
    "group_category": "Science",
    "section": "Section C",
    "practical_group": "C1",
    "name_en": "Md. Shakil Sheikh",
    "name_bn": "মোঃ শাকিল শেখ",
    "photo": "images/Shakil-326.jpg",
    "phone": "01894503342",
    "nid": "20096723306111722",
    "email": "",
    "gender": "Male",
    "dob": "08-Oct-2009",
    "blood_group": "O+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "MD. ALAM SHEIKH",
    "father_name_bn": "মোঃ আলম শেখ",
    "father_phone": "01718567402",
    "father_nid": "2830103046",
    "father_occ": "BUSINESS",
    "father_annual_income": 180000,
    "father_monthly_income": 15000,
    "mother_name_en": "ASMA BEGUM",
    "mother_name_bn": "আসমা বেগম",
    "mother_phone": "01821335668",
    "mother_nid": "5515833001",
    "local_guardian": "Md. Shamim sheikh",
    "present_address": "Village: Kanchan, Post:Kanchan-1461, U.P: Rupganj, Dist:Narayanganj District: Narayanganj",
    "permanent_address": "Village: Kanchan, Post:Kanchan-1461, U.P: Rupganj, Dist:Narayanganj District: Narayanganj",
    "district": "Narayanganj",
    "ssc_roll": "129636",
    "ssc_reg_no": "2210477983",
    "ssc_board": "Dhaka",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2025-2026",
    "ssc_division": "SSC - Science",
    "elective_subject": "Biology",
    "fourth_subject": "Higher Math",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "Shakil-129636-326.pdf",
    "pay_pdf_filename": "Shakil-129636-326.pdf",
    "app_pdf_path": "Application Form/Shakil-129636-326.pdf",
    "pay_pdf_path": "Payment Receipts/Shakil-129636-326.pdf",
    "photo_filename": "Shakil-326.jpg",
    "district_bn": "নারায়ণগঞ্জ",
    "upazila_district_bn": "কাঞ্চন, রূপগঞ্জ, নারায়ণগঞ্জ"
  },
  {
    "sl_no": 5,
    "student_id": "sasfkat5",
    "short_roll": "008",
    "full_class_roll": "1202526010008",
    "admission_roll": "431899",
    "hall_room": "",
    "group": "HSC - Science",
    "group_category": "Science",
    "section": "Section A",
    "practical_group": "A1",
    "name_en": "Shafkat Rahman",
    "name_bn": "শাফকাত রহমান",
    "photo": "images/safkat-008.jpg",
    "phone": "01996569688",
    "nid": "20108827508063779",
    "email": "shafkatrahmandkam@gmail.com",
    "gender": "Male",
    "dob": "01-Jan-2009",
    "blood_group": "O+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "MD. SHAHJAHAN ALI",
    "father_name_bn": "মোঃ শাহজাহান আলী",
    "father_phone": "01726981550",
    "father_nid": "8829408773679",
    "father_occ": "Teacher",
    "father_annual_income": 647760,
    "father_monthly_income": 53980,
    "mother_name_en": "SHARMIN SULTANA",
    "mother_name_bn": "শারমিন সুলতানা",
    "mother_phone": "01729634496",
    "mother_nid": "8216379274",
    "local_guardian": "",
    "present_address": "Village : Deboi Post : Birabo Thana : Rupganj District: Narayanganj",
    "permanent_address": "Village: Charnewargasa, Post : Ullapara R.S Thana : Ullapara District: Sirajganj",
    "district": "Sirajganj",
    "ssc_roll": "431899",
    "ssc_reg_no": "2218986978",
    "ssc_board": "Madrasah",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2023-2024",
    "ssc_division": "SSC - Science",
    "elective_subject": "Biology",
    "fourth_subject": "Higher Math",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "safkat-431899-008.pdf",
    "pay_pdf_filename": "safkat-431899-008.pdf",
    "app_pdf_path": "Application Form/safkat-431899-008.pdf",
    "pay_pdf_path": "Payment Receipts/safkat-431899-008.pdf",
    "photo_filename": "safkat-008.jpg",
    "district_bn": "সিরাজগঞ্জ",
    "upazila_district_bn": "চরনেওয়াদাগাছা, উল্লাপাড়া, সিরাজগঞ্জ"
  },
  {
    "sl_no": 6,
    "student_id": "munsi6",
    "short_roll": "022",
    "full_class_roll": "1202526010022",
    "admission_roll": "150493",
    "hall_room": "",
    "group": "HSC - Science",
    "group_category": "Science",
    "section": "Section A",
    "practical_group": "A1",
    "name_en": "Shahriar Al Sakib Munshi",
    "name_bn": "শাহরিয়ার আল সাকিব মুন্সী",
    "photo": "images/munsi-022.png",
    "phone": "01577203120",
    "nid": "20081927008007668",
    "email": "",
    "gender": "Male",
    "dob": "23-Dec-2008",
    "blood_group": "B+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "Shahneowaz Munshi",
    "father_name_bn": "শাহনেওয়াজ মুন্সী",
    "father_phone": "01319061472",
    "father_nid": "1918118566421",
    "father_occ": "",
    "father_annual_income": 0,
    "father_monthly_income": 0,
    "mother_name_en": "Musammat Sirina Akter",
    "mother_name_bn": "মোসাম্মৎ শিরিনা আক্তার",
    "mother_phone": "01749269156",
    "mother_nid": "3284149030",
    "local_guardian": "Sanjida Sultana Shanta 62 no house, opposite of comfort hospital, Green road, Dhaka 01319061472",
    "present_address": "Choto Alampur, Debidwar, Cumilla District: Comilla",
    "permanent_address": "Choto Alampur, Debidwar, Cumilla District: Comilla",
    "district": "Cumilla",
    "ssc_roll": "150493",
    "ssc_reg_no": "2211206546",
    "ssc_board": "Cumilla",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2025-2026",
    "ssc_division": "SSC - Science",
    "elective_subject": "Biology",
    "fourth_subject": "Higher Math",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "munsi-150493-022.pdf",
    "pay_pdf_filename": "munsi-150493-022.pdf",
    "app_pdf_path": "Application Form/munsi-150493-022.pdf",
    "pay_pdf_path": "Payment Receipts/munsi-150493-022.pdf",
    "photo_filename": "munsi-022.png",
    "district_bn": "কুমিল্লা",
    "upazila_district_bn": "ছোট আলমপুর, দেবীদ্বার, কুমিল্লা"
  },
  {
    "sl_no": 7,
    "student_id": "musfik7",
    "short_roll": "122",
    "full_class_roll": "1202526010122",
    "admission_roll": "170222",
    "hall_room": "",
    "group": "HSC - Science",
    "group_category": "Science",
    "section": "Section A",
    "practical_group": "A2",
    "name_en": "Md. Mushfiqur Rahman",
    "name_bn": "মোঃ মুশফিকুর রহমান মহিন",
    "photo": "images/musfik-122.jpg",
    "phone": "01767811792",
    "nid": "20090925006022498",
    "email": "mushfiq88bd@gmail.com",
    "gender": "Male",
    "dob": "21-Aug-2009",
    "blood_group": "A+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "MD. KAMAL HOSSAIN",
    "father_name_bn": "মোঃ কামাল হোসেন",
    "father_phone": "01726787445",
    "father_nid": "0916571524238",
    "father_occ": "Job",
    "father_annual_income": 240000,
    "father_monthly_income": 20000,
    "mother_name_en": "LUTFUN NAHAR",
    "mother_name_bn": "লুৎফুন নাহার",
    "mother_phone": "01316538033",
    "mother_nid": "0916571524239",
    "local_guardian": "MD. NURUL ISLAM Adarsha Para 6 no.ward, Charfassion,Bhola",
    "present_address": "Tenguri, Zirani, Savar,Dhaka District: Dhaka",
    "permanent_address": "South Sakuchia,Manpura,Bhola District: Bhola",
    "district": "Bhola",
    "ssc_roll": "170222",
    "ssc_reg_no": "2210580751",
    "ssc_board": "Dhaka",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2023-2024",
    "ssc_division": "SSC - Science",
    "elective_subject": "Higher Math",
    "fourth_subject": "Biology",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "musfik-170222-122.pdf",
    "pay_pdf_filename": "musfik-170222-122.pdf",
    "app_pdf_path": "Application Form/musfik-170222-122.pdf",
    "pay_pdf_path": "Payment Receipts/musfik-170222-122.pdf",
    "photo_filename": "musfik-122.jpg",
    "district_bn": "ভোলা",
    "upazila_district_bn": "দক্ষিণ সাকুচিয়া, মনপুরা, ভোলা"
  },
  {
    "sl_no": 8,
    "student_id": "esty8",
    "short_roll": "870",
    "full_class_roll": "1202526010870",
    "admission_roll": "112358",
    "hall_room": "",
    "group": "HSC - Science",
    "group_category": "Science",
    "section": "Section F",
    "practical_group": "F2",
    "name_en": "Taskin Rahman Esty",
    "name_bn": "তাসকিন রহমান এস্টি",
    "photo": "images/taskinesty-870.jpg",
    "phone": "01974097612",
    "nid": "20081591622101176",
    "email": "dhakaiyyaesty@gmail.com",
    "gender": "Male",
    "dob": "21-Aug-2008",
    "blood_group": "O+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "Mohammad Siddiqur Rahman",
    "father_name_bn": "মুহাম্মদ সিদ্দিকুর রহমান",
    "father_phone": "01714097613",
    "father_nid": "9104510004",
    "father_occ": "Banker",
    "father_annual_income": 700000,
    "father_monthly_income": 58333,
    "mother_name_en": "Anjuman Ara Arju",
    "mother_name_bn": "আঞ্জুমান আরা আরজু",
    "mother_phone": "01715370415",
    "mother_nid": "9151670859",
    "local_guardian": "Tanvir Rahman Efty Opposite of Enam medical College,Enam Medical Hostel, Thana Stand,Savar.",
    "present_address": "Present Address: Kamalghat Mazar Road,Sayed Monjil,(1st floor),purbi Mother Bari,po:GP0,ps:Sadarghat,Dist:Chattogram District: Dhaka",
    "permanent_address": "Permanent address:Vill+po=Kothuri,ps:Nawabgong,Dist:Dhaka. District: Dhaka",
    "district": "Dhaka",
    "ssc_roll": "112358",
    "ssc_reg_no": "2214308267",
    "ssc_board": "Chattogram",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2025-2026",
    "ssc_division": "SSC - Science",
    "elective_subject": "Higher Math",
    "fourth_subject": "Biology",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "taskinesty-112358-870.pdf",
    "pay_pdf_filename": "taskinesty-112358-870.pdf",
    "app_pdf_path": "Application Form/taskinesty-112358-870.pdf",
    "pay_pdf_path": "Payment Receipts/taskinesty-112358-870.pdf",
    "photo_filename": "taskinesty-870.jpg",
    "district_bn": "ঢাকা",
    "upazila_district_bn": "কোঠুরী, নবাবগঞ্জ, ঢাকা"
  },
  {
    "sl_no": 9,
    "student_id": "nafis9",
    "short_roll": "141",
    "full_class_roll": "1202526010141",
    "admission_roll": "268583",
    "hall_room": "",
    "group": "HSC - Science",
    "group_category": "Science",
    "section": "Section A",
    "practical_group": "A2",
    "name_en": "Nafis Alam Tarif",
    "name_bn": "মোঃ নাফিস আলম তারিফ",
    "photo": "images/nafis-141.jpg",
    "phone": "01738770330",
    "nid": "20089418615108694",
    "email": "tarifalam265@gmail.com",
    "gender": "Male",
    "dob": "12-Oct-2008",
    "blood_group": "O+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "MD NUHED ALAM",
    "father_name_bn": "মোঃ নূহেদ আলম",
    "father_phone": "01718355400",
    "father_nid": "3720050065",
    "father_occ": "Teacher",
    "father_annual_income": 500000,
    "father_monthly_income": 41667,
    "mother_name_en": "MST NILUFA IRIN",
    "mother_name_bn": "মোছাঃ নিলুফা আইরিন",
    "mother_phone": "01773702633",
    "mother_nid": "6420038223",
    "local_guardian": "",
    "present_address": "Bhangbari, Banglagar, Bachor, Ranisankal 5120 District: Thakurgaon",
    "permanent_address": "Bhangbari, Banglagar, Bachor, Ranisankal 5120 District: Thakurgaon",
    "district": "Thakurgaon",
    "ssc_roll": "268583",
    "ssc_reg_no": "2217803654",
    "ssc_board": "Dinajpur",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2023-2024",
    "ssc_division": "SSC - Science",
    "elective_subject": "Higher Math",
    "fourth_subject": "Biology",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "nafis-268583-141.pdf",
    "pay_pdf_filename": "nafis-268583-141.pdf",
    "app_pdf_path": "Application Form/nafis-268583-141.pdf",
    "pay_pdf_path": "Payment Receipts/nafis-268583-141.pdf",
    "photo_filename": "nafis-141.jpg",
    "district_bn": "ঠাকুরগাঁও",
    "upazila_district_bn": "ভাঙ্গবাড়ি, রানীশংকৈল, ঠাকুরগাঁও"
  },
  {
    "sl_no": 10,
    "student_id": "kayes10",
    "short_roll": "882",
    "full_class_roll": "1202526010882",
    "admission_roll": "1251031",
    "hall_room": "",
    "group": "HSC - Science",
    "group_category": "Science",
    "section": "Section F",
    "practical_group": "F2",
    "name_en": "Riasadul Islam Kayes",
    "name_bn": "রিয়াসাদুল ইসলাম কায়েস",
    "photo": "images/kayes-882.jpg",
    "phone": "01629171207",
    "nid": "2000822149952591",
    "email": "riasadulislamkayes@gmail.com",
    "gender": "Male",
    "dob": "13-Dec-2008",
    "blood_group": "A+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "MOHAMMAD ZAKARIA",
    "father_name_bn": "সাইদুল কাদের",
    "father_phone": "01610968370",
    "father_nid": "6013094161",
    "father_occ": "00",
    "father_annual_income": 0,
    "father_monthly_income": 0,
    "mother_name_en": "RASMIN AKTER",
    "mother_name_bn": "রেশমিন আক্তার",
    "mother_phone": "01328909453",
    "mother_nid": "6873191024",
    "local_guardian": "",
    "present_address": "732, Purba Cha-bagan, Malumghat (4743), Chakaria, Cox'sbazar District: Coxs Bazar",
    "permanent_address": "732, Purba Cha-bagan, Malumghat (4743), Chakaria, Cox'sbazar District: Coxs Bazar",
    "district": "Cox's Bazar",
    "ssc_roll": "125103",
    "ssc_reg_no": "2214426999",
    "ssc_board": "Chattogram",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2023-2024",
    "ssc_division": "SSC - Science",
    "elective_subject": "Higher Math",
    "fourth_subject": "Biology",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "kayes-1251031-882.pdf",
    "pay_pdf_filename": "kayes-1251031-882.pdf",
    "app_pdf_path": "Application Form/kayes-1251031-882.pdf",
    "pay_pdf_path": "Payment Receipts/kayes-1251031-882.pdf",
    "photo_filename": "kayes-882.jpg",
    "district_bn": "কক্সবাজার",
    "upazila_district_bn": "মালুমঘাট, চকরিয়া, কক্সবাজার"
  },
  {
    "sl_no": 11,
    "student_id": "jahid11",
    "short_roll": "223",
    "full_class_roll": "1202526010223",
    "admission_roll": "402416",
    "hall_room": "",
    "group": "HSC - Science",
    "group_category": "Science",
    "section": "Section B",
    "practical_group": "B1",
    "name_en": "Md. Jahidul Islam",
    "name_bn": "মোঃ জাহিদুল ইসলাম",
    "photo": "images/jahidvay-223.jpg",
    "phone": "01828246239",
    "nid": "2881766451",
    "email": "jkjahidultaskin10@gmail.com",
    "gender": "Male",
    "dob": "04-Apr-2006",
    "blood_group": "O+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "Khorshed Alam",
    "father_name_bn": "খোরশেদ আলম",
    "father_phone": "01828246239",
    "father_nid": "1000485001",
    "father_occ": "Farmer",
    "father_annual_income": 0,
    "father_monthly_income": 0,
    "mother_name_en": "Juosna Begum",
    "mother_name_bn": "জোৎস্না বেগম",
    "mother_phone": "",
    "mother_nid": "4150962522",
    "local_guardian": "",
    "present_address": "District: Narshingdi Subdistrict : Narshingdi Sadar Thanas: Madhabdi Post office : Chardigoldi District: Narsingdi",
    "permanent_address": "District: Narshingdi Subdistrict : Narshingdi Sadar Thanas: Madhabdi Post office : Chardigoldi District: Narsingdi",
    "district": "Narsingdi",
    "ssc_roll": "402416",
    "ssc_reg_no": "2218988796",
    "ssc_board": "Madrasah",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2025-2026",
    "ssc_division": "SSC - Science",
    "elective_subject": "Biology",
    "fourth_subject": "Higher Math",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "jahidvay-402416-223.pdf",
    "pay_pdf_filename": "jahidvay-402416-223.pdf",
    "app_pdf_path": "Application Form/jahidvay-402416-223.pdf",
    "pay_pdf_path": "Payment Receipts/jahidvay-402416-223.pdf",
    "photo_filename": "jahidvay-223.jpg",
    "district_bn": "নরসিংদী",
    "upazila_district_bn": "চরদিঘলদী, মাধবদী, নরসিংদী"
  },
  {
    "sl_no": 12,
    "student_id": "siam12",
    "short_roll": "195",
    "full_class_roll": "1202526010195",
    "admission_roll": "124282",
    "hall_room": "",
    "group": "HSC - Science",
    "group_category": "Science",
    "section": "Section B",
    "practical_group": "B1",
    "name_en": "Siam Hasan (Nator)",
    "name_bn": "সিয়াম হাসান",
    "photo": "images/siamnator-195.jpg",
    "phone": "01577234944",
    "nid": "20086914167108916",
    "email": "siamhasananik01@gmail.com",
    "gender": "Male",
    "dob": "17-Dec-2008",
    "blood_group": "B+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "Md. Sajedur Rahaman",
    "father_name_bn": "মোঃ সাজেদুর রহমান",
    "father_phone": "01761866285",
    "father_nid": "6914167989475",
    "father_occ": "Farmer",
    "father_annual_income": 250000,
    "father_monthly_income": 20833,
    "mother_name_en": "Mst. Onamika Khatun",
    "mother_name_bn": "মোছাঃ অনামিকা খাতুন",
    "mother_phone": "01804692801",
    "mother_nid": "6914167989476",
    "local_guardian": "Mridul Hasan Jagannath University, Phone: 01742090524",
    "present_address": "Vill.: Mashinda Majhpara, PO: Shikarpur, PS: Gurudaspur District: Natore",
    "permanent_address": "Vill.: Mashinda Majhpara, PO: Shikarpur, PS: Gurudaspur District: Natore",
    "district": "Natore",
    "ssc_roll": "124282",
    "ssc_reg_no": "2212668871",
    "ssc_board": "Rajshahi",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2023-2024",
    "ssc_division": "SSC - Science",
    "elective_subject": "Higher Math",
    "fourth_subject": "Statistics",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "siamnator-124282-195.pdf",
    "pay_pdf_filename": "siamnator-124282-195.pdf",
    "app_pdf_path": "Application Form/siamnator-124282-195.pdf",
    "pay_pdf_path": "Payment Receipts/siamnator-124282-195.pdf",
    "photo_filename": "siamnator-195.jpg",
    "district_bn": "নাটোর",
    "upazila_district_bn": "মশিন্দা মাঝপাড়া, গুরুদাসপুর, নাটোর"
  },
  {
    "sl_no": 13,
    "student_id": "siam13",
    "short_roll": "881",
    "full_class_roll": "1202526010881",
    "admission_roll": "626628",
    "hall_room": "",
    "group": "HSC - Science",
    "group_category": "Science",
    "section": "Section F",
    "practical_group": "F2",
    "name_en": "Md. Siam Ali (Kustia)",
    "name_bn": "মোঃ সিয়াম আলী",
    "photo": "images/siamkustia-881.jpg",
    "phone": "01705310841",
    "nid": "20075017917100088",
    "email": "",
    "gender": "Male",
    "dob": "05-Oct-2007",
    "blood_group": "O+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "Md.Robiul Islam",
    "father_name_bn": "মোঃ রবিউল ইসলাম",
    "father_phone": "01705633292",
    "father_nid": "5017917428460",
    "father_occ": "Immigrant",
    "father_annual_income": 0,
    "father_monthly_income": 0,
    "mother_name_en": "Mst.Sultana Khatun",
    "mother_name_bn": "মোছাঃ সুলতানা খাতুন",
    "mother_phone": "",
    "mother_nid": "",
    "local_guardian": "",
    "present_address": "District:",
    "permanent_address": "VILL: KHORDA AILCHARA , PO: KHORDA AILCHARA-7031, UPAZILA : KUSHTIA SADAR , DISTRICT: KUSHTIA District: Kushtia",
    "district": "Kushtia",
    "ssc_roll": "626628",
    "ssc_reg_no": "2213592495",
    "ssc_board": "Jashore",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2023-2024",
    "ssc_division": "SSC - Science",
    "elective_subject": "Higher Math",
    "fourth_subject": "Biology",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "siamkustia-626628-881.pdf",
    "pay_pdf_filename": "siamkustia-626628-881.pdf",
    "app_pdf_path": "Application Form/siamkustia-626628-881.pdf",
    "pay_pdf_path": "Payment Receipts/siamkustia-626628-881.pdf",
    "photo_filename": "siamkustia-881.jpg",
    "district_bn": "কুষ্টিয়া",
    "upazila_district_bn": "খোরদা আইলচারা, কুষ্টিয়া সদর, কুষ্টিয়া"
  },
  {
    "sl_no": 14,
    "student_id": "saimun14",
    "short_roll": "322",
    "full_class_roll": "1202526010322",
    "admission_roll": "160603",
    "hall_room": "",
    "group": "HSC - Science",
    "group_category": "Science",
    "section": "Section C",
    "practical_group": "C1",
    "name_en": "Saimun Islam",
    "name_bn": "মোঃ সাইমুন ইসলাম",
    "photo": "images/saimun-322.jpg",
    "phone": "01772589255",
    "nid": "20078815094111289",
    "email": "",
    "gender": "Male",
    "dob": "15-Sep-2007",
    "blood_group": "AB+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "Md Abu Syed",
    "father_name_bn": "মোঃ আবু সাঈদ",
    "father_phone": "01772589255",
    "father_nid": "19792699237986542",
    "father_occ": "",
    "father_annual_income": 0,
    "father_monthly_income": 0,
    "mother_name_en": "Mst Sabina Yeasmin",
    "mother_name_bn": "মোছাঃ সাবিনা ইয়াসমিন",
    "mother_phone": "01716697822",
    "mother_nid": "5070418420",
    "local_guardian": "Mst Nurjahan 01763164433",
    "present_address": "Pobnartek,Dhamsona,Savar,Dhaka District: Dhaka",
    "permanent_address": "Konabari,Rupsha,Kazipur,Sirajganj District: Sirajganj",
    "district": "Sirajganj",
    "ssc_roll": "160603",
    "ssc_reg_no": "2210583563",
    "ssc_board": "Rajshahi",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2023-2024",
    "ssc_division": "SSC - Science",
    "elective_subject": "Higher Math",
    "fourth_subject": "Biology",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "saimun-160603-322.pdf",
    "pay_pdf_filename": "saimun-160603-322.pdf",
    "app_pdf_path": "Application Form/saimun-160603-322.pdf",
    "pay_pdf_path": "Payment Receipts/saimun-160603-322.pdf",
    "photo_filename": "saimun-322.jpg",
    "district_bn": "সিরাজগঞ্জ",
    "upazila_district_bn": "কোনাবাড়ী, কাজিপুর, সিরাজগঞ্জ"
  },
  {
    "sl_no": 15,
    "student_id": "pranto15",
    "short_roll": "863",
    "full_class_roll": "1202526010863",
    "admission_roll": "625936",
    "hall_room": "",
    "group": "HSC - Science",
    "group_category": "Science",
    "section": "Section F",
    "practical_group": "F2",
    "name_en": "Ratul Hassan Pranto",
    "name_bn": "মোঃ রাতুল হাসান প্রান্ত",
    "photo": "images/pranto-863.png",
    "phone": "01995393323",
    "nid": "20105017931020671",
    "email": "ratulhasandc@gmail.com",
    "gender": "Male",
    "dob": "07-Feb-2010",
    "blood_group": "O+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "MD. ALTAF HOSSEN",
    "father_name_bn": "মোঃ আলতাফ হোসেন",
    "father_phone": "01740924480",
    "father_nid": "5057725680",
    "father_occ": "BUSINESSMAN",
    "father_annual_income": 250000,
    "father_monthly_income": 20833,
    "mother_name_en": "LATE. NAZMUN NAHAR",
    "mother_name_bn": "মৃত নাজমুন নাহার",
    "mother_phone": "",
    "mother_nid": "",
    "local_guardian": "MD. IKLACHUR RAHMAN Holding-3635,Shanti Nibash,Merajnagar,B-block, Rayerbag,Kodomtoli,Dhaka Mob: 01729767875",
    "present_address": "NOROHORIDIA, GOSWAMI DURGAPUR, KUSHTIA SADAR, KUSHTIA District: Kushtia",
    "permanent_address": "NOROHORIDIA, GOSWAMI DURGAPUR, KUSHTIA SADAR, KUSHTIA District: Kushtia",
    "district": "Kushtia",
    "ssc_roll": "625936",
    "ssc_reg_no": "2213576117",
    "ssc_board": "Jashore",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2023-2024",
    "ssc_division": "SSC - Science",
    "elective_subject": "Higher Math",
    "fourth_subject": "Biology",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "pranto-625936-863.pdf",
    "pay_pdf_filename": "pranto-625936-863.pdf",
    "app_pdf_path": "Application Form/pranto-625936-863.pdf",
    "pay_pdf_path": "Payment Receipts/pranto-625936-863.pdf",
    "photo_filename": "pranto-863.png",
    "district_bn": "কুষ্টিয়া",
    "upazila_district_bn": "নরহরিদিয়া, কুষ্টিয়া সদর, কুষ্টিয়া"
  },
  {
    "sl_no": 16,
    "student_id": "nayem18",
    "short_roll": "639",
    "full_class_roll": "1202526010639",
    "admission_roll": "603084",
    "hall_room": "",
    "group": "HSC - Science",
    "group_category": "Science",
    "section": "Section E",
    "practical_group": "E1",
    "name_en": "Nayeem Sarwar",
    "name_bn": "নাঈম সরওয়ার",
    "photo": "images/neyem-639.jpg",
    "phone": "01331198715",
    "nid": "20105017956031586",
    "email": "",
    "gender": "Male",
    "dob": "31-Dec-2010",
    "blood_group": "O+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "ABU SHAID MD. GOLAM SORWAR",
    "father_name_bn": "আবু সাঈদ মোঃ গোলাম সরওয়ার",
    "father_phone": "01711985399",
    "father_nid": "8676330411",
    "father_occ": "Representative",
    "father_annual_income": 0,
    "father_monthly_income": 0,
    "mother_name_en": "SAMSUN NAHAR",
    "mother_name_bn": "সামসুননাহার",
    "mother_phone": "01735737581",
    "mother_nid": "",
    "local_guardian": "Vill: College Para, PO: Alamdanga, PS: Alamdanga",
    "present_address": "Vill: College Para, PO: Alamdanga, PS: Alamdanga District: Chuadanga",
    "permanent_address": "Vill: College Para, PO: Alamdanga, PS: Alamdanga District: Chuadanga",
    "district": "Chuadanga",
    "ssc_roll": "603084",
    "ssc_reg_no": "2213415705",
    "ssc_board": "Jashore",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2023-2024",
    "ssc_division": "SSC - Science",
    "elective_subject": "Higher Math",
    "fourth_subject": "Biology",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "neyem-603084-639.pdf",
    "pay_pdf_filename": "neyem-603084-639.pdf",
    "app_pdf_path": "Application Form/neyem-603084-639.pdf",
    "pay_pdf_path": "Payment Receipts/neyem-603084-639.pdf",
    "photo_filename": "neyem-639.jpg",
    "district_bn": "চুয়াডাঙ্গা",
    "upazila_district_bn": "কলেজ পাড়া, আলমডাঙ্গা, চুয়াডাঙ্গা"
  },
  {
    "sl_no": 17,
    "student_id": "alauddin17",
    "short_roll": "140",
    "full_class_roll": "1202526030140",
    "admission_roll": "760532",
    "hall_room": "",
    "group": "HSC - Humanities",
    "group_category": "Humanities",
    "section": "N/A",
    "practical_group": "N/A",
    "name_en": "Md. Alauddin Mollah",
    "name_bn": "মোঃ আলাউদ্দিন মোল্লা",
    "photo": "images/alawddin-140.jpg",
    "phone": "01914476860",
    "nid": "20096515247025076",
    "email": "",
    "gender": "Male",
    "dob": "09-Sep-2009",
    "blood_group": "O+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "MD. ISHAQUE MOLLAH",
    "father_name_bn": "মোঃ ইসাহাক মোল্লা",
    "father_phone": "01956324329",
    "father_nid": "5070954507",
    "father_occ": "Business",
    "father_annual_income": 96000,
    "father_monthly_income": 8000,
    "mother_name_en": "SUFEA",
    "mother_name_bn": "সুফিয়া",
    "mother_phone": "",
    "mother_nid": "5520955922",
    "local_guardian": "",
    "present_address": "Village: Kalisongkorpur, Post Office: Joshobontopur, P/S: Mohammadpur, Dist: Magura District: Magura",
    "permanent_address": "Village: Kalisongkorpur, Post Office: Joshobontopur, P/S: Mohammadpur, Dist: Magura District: Magura",
    "district": "Magura",
    "ssc_roll": "760532",
    "ssc_reg_no": "2213529214",
    "ssc_board": "Jashore",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2023-2024",
    "ssc_division": "SSC - Humanities",
    "elective_subject": "Logic, Civics, History",
    "fourth_subject": "Psychology",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "alawddin-760532-140.pdf",
    "pay_pdf_filename": "alawddin-760532-140.pdf",
    "app_pdf_path": "Application Form/alawddin-760532-140.pdf",
    "pay_pdf_path": "Payment Receipts/alawddin-760532-140.pdf",
    "photo_filename": "alawddin-140.jpg",
    "district_bn": "মাগুরা",
    "upazila_district_bn": "কালিশংকরপুর, মহম্মদপুর, মাগুরা"
  },
  {
    "sl_no": 18,
    "student_id": "rafiq18",
    "short_roll": "872",
    "full_class_roll": "1202526010872",
    "admission_roll": "621741",
    "hall_room": "",
    "group": "HSC - Science",
    "group_category": "Science",
    "section": "Section F",
    "practical_group": "F2",
    "name_en": "Md. Rafiq Bin Nizam",
    "name_bn": "মোঃ রফিক বিন নিজাম",
    "photo": "images/rafiq-872.jpg",
    "phone": "01342909383",
    "nid": "20085013994102055",
    "email": "",
    "gender": "Male",
    "dob": "24-Dec-2008",
    "blood_group": "O+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "MD. ZAFIRUL ISLAM",
    "father_name_bn": "মোঃ জাফিরুল ইসলাম",
    "father_phone": "01775208547",
    "father_nid": "9123681554",
    "father_occ": "TEACHER",
    "father_annual_income": 100000,
    "father_monthly_income": 8333,
    "mother_name_en": "MST. RABIA BASRY",
    "mother_name_bn": "মোছাঃ রাবিয়া বসরী",
    "mother_phone": "01342909383",
    "mother_nid": "3723494542",
    "local_guardian": "MD. ZAFIRUL ISLAM RIFAITPUR, DAULATPUR, KUSHTIA",
    "present_address": "RIFAITPUR, DAULATPUR, KUSHTIA District: Kushtia",
    "permanent_address": "RIFAITPUR, DAULATPUR, KUSHTIA District: Kushtia",
    "district": "Kushtia",
    "ssc_roll": "621741",
    "ssc_reg_no": "2213505414",
    "ssc_board": "Jashore",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2023-2024",
    "ssc_division": "SSC - Science",
    "elective_subject": "Higher Math",
    "fourth_subject": "Biology",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "rafiq-621741-872.pdf",
    "pay_pdf_filename": "rafiq-621741-872.pdf",
    "app_pdf_path": "Application Form/rafiq-621741-872.pdf",
    "pay_pdf_path": "Payment Receipts/rafiq-621741-872.pdf",
    "photo_filename": "rafiq-872.jpg",
    "district_bn": "কুষ্টিয়া",
    "upazila_district_bn": "রিফায়েতপুর, দৌলতপুর, কুষ্টিয়া"
  },
  {
    "sl_no": 19,
    "student_id": "riyad19",
    "short_roll": "596",
    "full_class_roll": "1202526010596",
    "admission_roll": "223802",
    "hall_room": "",
    "group": "HSC - Science",
    "group_category": "Science",
    "section": "Section D",
    "practical_group": "D2",
    "name_en": "Tashfiqur Rahman Riyad",
    "name_bn": "তাশফিকুর রহমান রিয়াদ",
    "photo": "images/riyad-596.jpg",
    "phone": "01732168077",
    "nid": "20096716879108282",
    "email": "tashfiqurrahmanriyad2009@gmail.com",
    "gender": "Male",
    "dob": "17-May-2009",
    "blood_group": "B+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "Md. Masum Miah",
    "father_name_bn": "মাসুম মিয়া",
    "father_phone": "01732168077",
    "father_nid": "8689534142",
    "father_occ": "farmer",
    "father_annual_income": 130000,
    "father_monthly_income": 10833,
    "mother_name_en": "Tasmin Akter",
    "mother_name_bn": "তাসমিন আক্তার",
    "mother_phone": "01748492314",
    "mother_nid": "",
    "local_guardian": "",
    "present_address": "purbachal, Rupganj, Narayanganj District: Narayanganj",
    "permanent_address": "purbachal, Rupganj, Narayanganj District: Narayanganj",
    "district": "Narayanganj",
    "ssc_roll": "223802",
    "ssc_reg_no": "2210476765",
    "ssc_board": "Dhaka",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2023-2024",
    "ssc_division": "SSC - Science",
    "elective_subject": "Higher Math",
    "fourth_subject": "Biology",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "riyad-223802-596.pdf",
    "pay_pdf_filename": "riyad-223802-596.pdf",
    "app_pdf_path": "Application Form/riyad-223802-596.pdf",
    "pay_pdf_path": "Payment Receipts/riyad-223802-596.pdf",
    "photo_filename": "riyad-596.jpg",
    "district_bn": "নারায়ণগঞ্জ",
    "upazila_district_bn": "পূর্বাচল, রূপগঞ্জ, নারায়ণগঞ্জ"
  },
  {
    "sl_no": 20,
    "student_id": "mosih20",
    "short_roll": "332",
    "full_class_roll": "1202526010332",
    "admission_roll": "120725",
    "hall_room": "",
    "group": "HSC - Science",
    "group_category": "Science",
    "section": "Section C",
    "practical_group": "C1",
    "name_en": "Md. Chisty Islam Mosih",
    "name_bn": "মোঃ চিশতী ইসলাম মসীহ",
    "photo": "images/mosih-332.jpg",
    "phone": "01320823354",
    "nid": "20096914485110975",
    "email": "",
    "gender": "Male",
    "dob": "30-May-2009",
    "blood_group": "A+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "MD BOZLUR RAHMAN",
    "father_name_bn": "মোঃ বজলুর রহমান",
    "father_phone": "01763073516",
    "father_nid": "4618270070",
    "father_occ": "Tailor",
    "father_annual_income": 0,
    "father_monthly_income": 0,
    "mother_name_en": "MST AKHI BEGUM",
    "mother_name_bn": "মোছাঃ আঁখি বেগম",
    "mother_phone": "01763969259",
    "mother_nid": "9559018412",
    "local_guardian": "",
    "present_address": "Village: Dokkin Lalpur, Post: Lalpur, P.S: Lalpur, District: Natore. District: Natore",
    "permanent_address": "Village: Dokkin Lalpur, Post: Lalpur, P.S: Lalpur, District: Natore. District: Natore",
    "district": "Natore",
    "ssc_roll": "120725",
    "ssc_reg_no": "2212669969",
    "ssc_board": "Rajshahi",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2023-2024",
    "ssc_division": "SSC - Science",
    "elective_subject": "Higher Math",
    "fourth_subject": "Biology",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "mosih-120725-332.pdf",
    "pay_pdf_filename": "mosih-120725-332.pdf",
    "app_pdf_path": "Application Form/mosih-120725-332.pdf",
    "pay_pdf_path": "Payment Receipts/mosih-120725-332.pdf",
    "photo_filename": "mosih-332.jpg",
    "district_bn": "নাটোর",
    "upazila_district_bn": "দক্ষিণ লালপুর, লালপুর, নাটোর"
  },
  {
    "sl_no": 21,
    "student_id": "abrar21",
    "short_roll": "200",
    "full_class_roll": "1202526010200",
    "admission_roll": "638769",
    "hall_room": "",
    "group": "HSC - Science",
    "group_category": "Science",
    "section": "Section B",
    "practical_group": "B1",
    "name_en": "Md. Ahanaf Abrar",
    "name_bn": "মোঃ আহনাফ আবরার",
    "photo": "images/abrar-200.jpg",
    "phone": "01515288692",
    "nid": "20094418018103983",
    "email": "abrarislam0723@gmail.com",
    "gender": "Male",
    "dob": "01-Jan-2009",
    "blood_group": "B+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "MD. JAHANGIR HOSSAIN",
    "father_name_bn": "মোঃ জাহাঙ্গীর হোসেন",
    "father_phone": "01723510651",
    "father_nid": "3713137051",
    "father_occ": "Teacher",
    "father_annual_income": 210000,
    "father_monthly_income": 17500,
    "mother_name_en": "MST. JOLY KHATUN",
    "mother_name_bn": "মোছাঃ জলি খাতুন",
    "mother_phone": "01754433313",
    "mother_nid": "2389501806",
    "local_guardian": "MD. SERAJUS SALEKIN PORAG 429/B Malibag Chowdhury para, Near by Matir Mosjid, Opposite side of walton service point, Rampura, Dhaka, Phone: 01915336051",
    "present_address": "429/B Malibag Chowdhury para, Near by Matir Mosjid, Opposite side of walton service point, Rampura, Dhaka District: Dhaka",
    "permanent_address": "Village: Dhawra, P.O: Dhawra(7320), P.S: Shailkupa District: Jhenaidah",
    "district": "Jhenaidah",
    "ssc_roll": "638769",
    "ssc_reg_no": "2213474821",
    "ssc_board": "Jashore",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2023-2024",
    "ssc_division": "SSC - Science",
    "elective_subject": "Higher Math",
    "fourth_subject": "Biology",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "abrar-638769-200.pdf",
    "pay_pdf_filename": "abrar-638769-200.pdf",
    "app_pdf_path": "Application Form/abrar-638769-200.pdf",
    "pay_pdf_path": "Payment Receipts/abrar-638769-200.pdf",
    "photo_filename": "abrar-200.jpg",
    "district_bn": "ঝিনাইদহ",
    "upazila_district_bn": "ধৌড়া, শৈলকুপা, ঝিনাইদহ"
  },
  {
    "sl_no": 22,
    "student_id": "rudro22",
    "short_roll": "100",
    "full_class_roll": "1202526020100",
    "admission_roll": "146693",
    "hall_room": "",
    "group": "HSC - Business Studies",
    "group_category": "Business Studies",
    "section": "N/A",
    "practical_group": "N/A",
    "name_en": "M M Tanvir (Rudro)",
    "name_bn": "এম এম তানভীর (রুদ্র)",
    "photo": "images/rudro-100.jpg",
    "phone": "01516547125",
    "nid": "20087618317037989",
    "email": "",
    "gender": "Male",
    "dob": "04-Jun-2008",
    "blood_group": "B+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "MD RAFIQUL ISLAM",
    "father_name_bn": "মোঃ রফিকুল ইসলাম",
    "father_phone": "01751723978",
    "father_nid": "7300868689",
    "father_occ": "TECAHER",
    "father_annual_income": 426000,
    "father_monthly_income": 35500,
    "mother_name_en": "MST TASLIMA KHATUN SUFIA",
    "mother_name_bn": "মোছাঃ তাসলিমা খাতুন সুফিয়া",
    "mother_phone": "01714526234",
    "mother_nid": "1900860469",
    "local_guardian": "",
    "present_address": "BONKOLA, BONKOLA-6662, SUJANAGAR, PABNA District: Pabna",
    "permanent_address": "BOALIA, AHAMMADPUR-6682, SUJANAGAR, PABNA District: Pabna",
    "district": "Pabna",
    "ssc_roll": "146693",
    "ssc_reg_no": "2212728447",
    "ssc_board": "Rajshahi",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2023-2024",
    "ssc_division": "SSC - Science",
    "elective_subject": "Finance, Banking & Insurance",
    "fourth_subject": "Statistics",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "rudro-146693-100.pdf",
    "pay_pdf_filename": "rudro-146693-100.pdf",
    "app_pdf_path": "Application Form/rudro-146693-100.pdf",
    "pay_pdf_path": "Payment Receipts/rudro-146693-100.pdf",
    "photo_filename": "rudro-100.jpg",
    "district_bn": "পাবনা",
    "upazila_district_bn": "বোয়ালিয়া, সুজানগর, পাবনা"
  },
  {
    "sl_no": 23,
    "student_id": "riasad23",
    "short_roll": "337",
    "full_class_roll": "1202526010337",
    "admission_roll": "625467",
    "hall_room": "",
    "group": "HSC - Science",
    "group_category": "Science",
    "section": "Section C",
    "practical_group": "C1",
    "name_en": "Sobhan Mahmud Khan (Riasad)",
    "name_bn": "সোবহান মাহমুদ খান (রিয়াসাদ)",
    "photo": "images/riasad-337.jpg",
    "phone": "01922407329",
    "nid": "20095013967110300",
    "email": "",
    "gender": "Male",
    "dob": "26-Jul-2009",
    "blood_group": "O+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "MAHABUB KHAN",
    "father_name_bn": "মাহাবুব খাঁন",
    "father_phone": "01739269792",
    "father_nid": "5534048573",
    "father_occ": "Business",
    "father_annual_income": 250000,
    "father_monthly_income": 20833,
    "mother_name_en": "MST LUTHFUNNAHAR SHIMU",
    "mother_name_bn": "মোসাঃ লুৎফুন্নাহার শিমু",
    "mother_phone": "01400924562",
    "mother_nid": "19845013967914142",
    "local_guardian": "ABUL KALAM AZAD MUKDA, MOTIJIL, DHAKA, 01722337139",
    "present_address": "NOTUN AMDOHO ALLARDARGA, DAULATPUR District: Kushtia",
    "permanent_address": "NOTUN AMDOHO ALLARDARGA, DAULATPUR District: Kushtia",
    "district": "Kushtia",
    "ssc_roll": "625467",
    "ssc_reg_no": "2213518137",
    "ssc_board": "Jashore",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2023-2024",
    "ssc_division": "SSC - Science",
    "elective_subject": "Biology",
    "fourth_subject": "Higher Math",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "riasad-625467-337.pdf",
    "pay_pdf_filename": "riasad-625467-337.pdf",
    "app_pdf_path": "Application Form/riasad-625467-337.pdf",
    "pay_pdf_path": "Payment Receipts/riasad-625467-337.pdf",
    "photo_filename": "riasad-337.jpg",
    "district_bn": "কুষ্টিয়া",
    "upazila_district_bn": "নতুন আমদহ, দৌলতপুর, কুষ্টিয়া"
  },
  {
    "sl_no": 24,
    "student_id": "musa24",
    "short_roll": "213",
    "full_class_roll": "1202526010213",
    "admission_roll": "425780",
    "hall_room": "",
    "group": "HSC - Science",
    "group_category": "Science",
    "section": "Section B",
    "practical_group": "B1",
    "name_en": "Mahbubur Rahman Musa",
    "name_bn": "মাহবুবুর রহমান মুসা",
    "photo": "images/musa-213.jpg",
    "phone": "01603359325",
    "nid": "20094218440000509",
    "email": "mahbuburrahmanmusa99@gmail.com",
    "gender": "Male",
    "dob": "10-Apr-2009",
    "blood_group": "A+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "MD MIJANUR RAHMAN",
    "father_name_bn": "মোঃ মিজানুর রহমান",
    "father_phone": "01718450916",
    "father_nid": "5988867577",
    "father_occ": "Teacher",
    "father_annual_income": 0,
    "father_monthly_income": 0,
    "mother_name_en": "JESMIN AKTER",
    "mother_name_bn": "জেসমিন আক্তার",
    "mother_phone": "01735017728",
    "mother_nid": "3736866298",
    "local_guardian": "Mahabuba Rahman Nabila বাঘড়ী, রাজাপুর,, ঝালকািঠ, বিরশাল, ঢাকা, বাংলােদশ।",
    "present_address": "বাঘড়ী, রাজাপুর,, ঝালকািঠ, বিরশাল, ঢাকা, বাংলােদশ। District: Jhalakati",
    "permanent_address": "বাঘড়ী, রাজাপুর,, ঝালকািঠ, বিরশাল, ঢাকা, বাংলােদশ। District: Jhalakati",
    "district": "Jhalakathi",
    "ssc_roll": "425780",
    "ssc_reg_no": "2218729335",
    "ssc_board": "Madrasah",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2023-2024",
    "ssc_division": "SSC - Science",
    "elective_subject": "Higher Math",
    "fourth_subject": "Biology",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "musa-425780-213.pdf",
    "pay_pdf_filename": "musa-425780-213.pdf",
    "app_pdf_path": "Application Form/musa-425780-213.pdf",
    "pay_pdf_path": "Payment Receipts/musa-425780-213.pdf",
    "photo_filename": "musa-213.jpg",
    "district_bn": "ঝালকাঠি",
    "upazila_district_bn": "বাঘড়ী, রাজাপুর, ঝালকাঠি"
  },
  {
    "sl_no": 25,
    "student_id": "ariful25",
    "short_roll": "050",
    "full_class_roll": "1202526010050",
    "admission_roll": "116995",
    "hall_room": "",
    "group": "HSC - Science",
    "group_category": "Science",
    "section": "Section A",
    "practical_group": "A1",
    "name_en": "Ariful Islam",
    "name_bn": "মোঃ আরিফুল ইসলাম",
    "photo": "images/ariful-050.jpg",
    "phone": "01848631025",
    "nid": "20097024406005812",
    "email": "arifulislam20238086@gmail.com",
    "gender": "Male",
    "dob": "21-Sep-2009",
    "blood_group": "O+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "M. AZIZUL ISLAM",
    "father_name_bn": "মোঃ আজিজুল ইসলাম",
    "father_phone": "01738114130",
    "father_nid": "5526854657",
    "father_occ": "Farmer",
    "father_annual_income": 84000,
    "father_monthly_income": 7000,
    "mother_name_en": "MST NAZMA BEGUM",
    "mother_name_bn": "মোসাঃ নাজমা বেগম",
    "mother_phone": "01798720802",
    "mother_nid": "6876859635",
    "local_guardian": "M. NAJMUL ISLAM 121/1,Dewan palace, West Agargaon, Dhaka (1207) Phone number :01752588234",
    "present_address": "P.M COLLEGE PARA, ROHANPUR (6320), Rahanpur Paurashava,Gomastapur,Chapainawabganj District: Nawabganj",
    "permanent_address": "P.M COLLEGE PARA, ROHANPUR (6320), Rahanpur Paurashava,Gomastapur,Chapainawabganj District: Nawabganj",
    "district": "Chapai Nawabganj",
    "ssc_roll": "116995",
    "ssc_reg_no": "2212651048",
    "ssc_board": "Rajshahi",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2025-2026",
    "ssc_division": "SSC - Science",
    "elective_subject": "Biology",
    "fourth_subject": "Higher Math",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "ariful-116995-050.pdf",
    "pay_pdf_filename": "ariful-116995-050.pdf",
    "app_pdf_path": "Application Form/ariful-116995-050.pdf",
    "pay_pdf_path": "Payment Receipts/ariful-116995-050.pdf",
    "photo_filename": "ariful-050.jpg",
    "district_bn": "চাঁপাইনবাবগঞ্জ",
    "upazila_district_bn": "রহনপুর, গোমস্তাপুর, চাঁপাইনবাবগঞ্জ"
  },
  {
    "sl_no": 26,
    "student_id": "rejawl26",
    "short_roll": "098",
    "full_class_roll": "1202526030098",
    "admission_roll": "164810",
    "hall_room": "",
    "group": "HSC - Humanities",
    "group_category": "Humanities",
    "section": "N/A",
    "practical_group": "N/A",
    "name_en": "Md Rezaul Karim",
    "name_bn": "মোঃ রেজাউল করিম",
    "photo": "images/rejawl-098.png",
    "phone": "01641659606",
    "nid": "20081919477101846",
    "email": "rkdc8989@gmail.com",
    "gender": "Male",
    "dob": "10-Sep-2008",
    "blood_group": "A+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "TOFAZZOL HOSSEN",
    "father_name_bn": "তোফাজ্জল হোসেন",
    "father_phone": "01820098153",
    "father_nid": "1918131647683",
    "father_occ": "",
    "father_annual_income": 0,
    "father_monthly_income": 0,
    "mother_name_en": "MST RANU BEGUM",
    "mother_name_bn": "মোসাঃ রানু বেগম",
    "mother_phone": "",
    "mother_nid": "1918131647683",
    "local_guardian": "",
    "present_address": "VILLAGE: TULAKANDI, POST OFFICE: NARANDIA-3519, POLICE STATION: TITAS District: Comilla",
    "permanent_address": "VILLAGE: TULAKANDI, POST OFFICE: NARANDIA-3519, POLICE STATION: TITAS District: Comilla",
    "district": "Cumilla",
    "ssc_roll": "164810",
    "ssc_reg_no": "2211189763",
    "ssc_board": "Cumilla",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2023-2024",
    "ssc_division": "SSC - Science",
    "elective_subject": "Geography, Economics, Civics",
    "fourth_subject": "Psychology",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "rejawl-164810-098.pdf",
    "pay_pdf_filename": "rejawl-164810-098.pdf",
    "app_pdf_path": "Application Form/rejawl-164810-098.pdf",
    "pay_pdf_path": "Payment Receipts/rejawl-164810-098.pdf",
    "photo_filename": "rejawl-098.png",
    "district_bn": "কুমিল্লা",
    "upazila_district_bn": "তুলাকান্দি, তিতাস, কুমিল্লা"
  },
  {
    "sl_no": 27,
    "student_id": "sabit27",
    "short_roll": "171",
    "full_class_roll": "1202526010171",
    "admission_roll": "633221",
    "hall_room": "",
    "group": "HSC - Science",
    "group_category": "Science",
    "section": "Section B",
    "practical_group": "B1",
    "name_en": "Muhammad Rayhanoor Sabit",
    "name_bn": "মুহাম্মদ রায়হানুর সাবিত",
    "photo": "images/sabit-171.jpg",
    "phone": "01852223068",
    "nid": "20096515223030788",
    "email": "",
    "gender": "Male",
    "dob": "11-Feb-2009",
    "blood_group": "AB+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "Md. Abul Kasham",
    "father_name_bn": "মোঃ আবুল কাশেম",
    "father_phone": "01971444941",
    "father_nid": "5087319975",
    "father_occ": "Farmer",
    "father_annual_income": 72000,
    "father_monthly_income": 6000,
    "mother_name_en": "Mst. Salma Begum",
    "mother_name_bn": "মোছাঃ সালমা বেগম",
    "mother_phone": "",
    "mother_nid": "",
    "local_guardian": "",
    "present_address": "District:",
    "permanent_address": "Marich Pasha, Lohagara District: Narail",
    "district": "Narail",
    "ssc_roll": "633221",
    "ssc_reg_no": "2213550272",
    "ssc_board": "Jashore",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2023-2024",
    "ssc_division": "SSC - Science",
    "elective_subject": "Higher Math",
    "fourth_subject": "Biology",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "sabit-633221-171.pdf",
    "pay_pdf_filename": "sabit-633221-171.pdf",
    "app_pdf_path": "Application Form/sabit-633221-171.pdf",
    "pay_pdf_path": "Payment Receipts/sabit-633221-171.pdf",
    "photo_filename": "sabit-171.jpg",
    "district_bn": "নড়াইল",
    "upazila_district_bn": "মরিচ পাশা, লোহাগড়া, নড়াইল"
  },
  {
    "sl_no": 28,
    "student_id": "alif28",
    "short_roll": "153",
    "full_class_roll": "1202526010153",
    "admission_roll": "211619",
    "hall_room": "",
    "group": "HSC - Science",
    "group_category": "Science",
    "section": "Section B",
    "practical_group": "B1",
    "name_en": "Alimuzzamann Alif",
    "name_bn": "মোঃ আলিমুজ্জামান আলিফ",
    "photo": "images/alif-153.jpg",
    "phone": "01758173284",
    "nid": "20083219175113917",
    "email": "mdalimuzzamanalif890@gmail.com",
    "gender": "Male",
    "dob": "11-Nov-2008",
    "blood_group": "AB+",
    "religion": "Islam",
    "nationality": "Bangladeshi",
    "father_name_en": "MD. NUR ZAMAN MIA",
    "father_name_bn": "মোঃ নুর জামান মিয়া",
    "father_phone": "01717909568",
    "father_nid": "2819190592",
    "father_occ": "Clerk",
    "father_annual_income": 500000,
    "father_monthly_income": 41667,
    "mother_name_en": "MST. AYESHA SIDDIKA",
    "mother_name_bn": "মোছাঃ আয়েশা সিদ্দিকা",
    "mother_phone": "01761206311",
    "mother_nid": "4619557699",
    "local_guardian": "MD NAZMUL HAQUE Dhaka Cantonment, Dhaka Cell: 01722823703",
    "present_address": "Purbo Bach Hati, Ramganj, Sarbananda, Sundarganj, Gaibandha. District: Gaibandha",
    "permanent_address": "Purbo Bach Hati, Ramganj, Sarbananda, Sundarganj, Gaibandha. District: Gaibandha",
    "district": "Gaibandha",
    "ssc_roll": "211619",
    "ssc_reg_no": "2217656386",
    "ssc_board": "Dinajpur",
    "ssc_year": "2025",
    "ssc_gpa": "5.00",
    "ssc_session": "2023-2024",
    "ssc_division": "SSC - Science",
    "elective_subject": "Biology",
    "fourth_subject": "Higher Math",
    "admission_session": "2025-2026",
    "hall_name": "International Hall",
    "app_pdf_filename": "alif-211619-153.pdf",
    "pay_pdf_filename": "alif-211619-153.pdf",
    "app_pdf_path": "Application Form/alif-211619-153.pdf",
    "pay_pdf_path": "Payment Receipts/alif-211619-153.pdf",
    "photo_filename": "alif-153.jpg",
    "district_bn": "গাইবান্ধা",
    "upazila_district_bn": "পূর্ব বাচহাটি, সুন্দরগঞ্জ, গাইবান্ধা"
  }
];
